name: Release Platform Archives
on: [push]
jobs:
  release-platform-archives:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Files for macOS Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'macos.tgz'
          type: 'tar'
          directory: 'files/macos'
      - name: Upload macOS Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "macos.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
